name: sportapplication
description: sport_Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get: ^4.1.3
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^9.0.0
  shared_preferences: ^2.0.4
  cached_network_image: ^2.5.0
  shimmer: ^1.1.2
  flutter_svg:
  flutter_masked_text: ^0.8.0
  pin_code_text_field: ^1.7.1
  google_maps_flutter: ^1.2.0
  geolocator: ^6.2.1
  flutter_widget_from_html: ^0.5.2+1
  flutter_spinkit: "^4.1.2"
  grouped_buttons: ^1.0.4
  url_launcher: ^5.7.10
  dotted_border: ^1.0.6
  image_picker: ^0.6.7+4
  image_cropper: ^1.3.1
  persian_datetime_picker: ^2.1.1
  barcode_scan_fix: ^1.0.2
  syncfusion_flutter_barcodes: ^19.1.58
  material_tag_editor: ^0.1.1
  package_info: ^2.0.0
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.0
  fluttertoast: ^8.0.7
  lottie: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/
    - assets/json/

  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/Yekan.ttf
    - family: sanse
      fonts:
        - asset: assets/fonts/sansbold.ttf
          weight: 700
        - asset: assets/fonts/sansnormal.ttf
          weight: 100

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
