name: sportapplication
description: sport_Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get: ^4.1.3
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^9.0.0
  shared_preferences: ^2.0.4
  cached_network_image: ^2.5.0
  shimmer: ^1.1.2
  flutter_svg: ^0.21.0+1
  flutter_masked_text: ^0.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/
  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/Yekan.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
